### ISSUE TITLE
79fb03f4 test is unsolvable, water flow

### ISSUE THREAD

**Issue by neoneye** [fchollet/ARC-AGI#100]
# Problem

[ARC-Interactive](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=79fb03f4)

### My first prediction

My reasoning.
- It seems water can flow backwards into holes. maybe water can flow forward into a hole.

![Screenshot 2024-02-25 at 02 04 43 copy](https://github.com/fchollet/ARC/assets/147971/5ecd92d7-10a7-4db1-9838-9b0f2f1e26ac)

### My second prediction

My reasoning.
- Guide the water above the hole obstacle, without sending any water below the obstacle.

![Screenshot 2024-02-25 at 02 09 55 copy](https://github.com/fchollet/ARC/assets/147971/79c64af1-c52c-4bd3-b618-0dd73d7c3dff)

At this point I looked at what was the expected result. 

### Expected 
![expected](https://github.com/fchollet/ARC/assets/147971/3a01e736-9003-4e3f-9beb-7b1df781baa0)

I'm quite surprised to see that the water flows into the hole. But not around the entire structure. It seems like a mistake.

There is no example among the `train` pairs, that shows this behavior.

# Solution

Tweak one of the `train` pairs, so it demonstrates what to do in similar scenarios.

**Comment by CerebralAdvantage** [comment]
It's true, the train pairs do not train for this specific situation, and it seems very difficult.  I solved it the first try.  The key to solving it is not overthinking what is happening.  There are very few things that the "water" actually does.  Because it splits around a "stone", it can then do two things... until it passes said stone.  After which, it needs to continue, immediately in line with the obstacle, as a single stream.  The area in question is very concerning, but only if you get carried away with your narrative.  I know that last statement doesn't help.  It is 100% solvable.  Try thinking more "simply."

AGI enthusiasts bonus for being gihub-savvy: note the use of "water" and "stone," something most adults have experience with (I grew up in a forest).  How can one possibly help a machine relate to these "naturally human" ideas?  Answer that question, and your code might do quite well!  Hint:  Grab a billion photos of hillside creeks from the world wide web... not!

**Comment by CerebralAdvantage** [comment]
That said, example 5 output is quite incorrect.  The middle stone has its flow blocked, and it should only continue after the upper and lower stone.  It definitely should not be flowing back uphill.  I would love to be corrected.
If there are these tiny errors in the examples, someone (or some thing...) attempting to use every detail of every example will fail.  As a human, I simply ignored the complexity of 5 output.  But after further thought ("Agua...") I want back to the crime scene and sure enough, the wrongness is apparent.  -- 

Since it *is* solvable, then the 5 output *must be* incorrect.  Otherwise, @neoneye's "if it can flow uphill" comment would totally hold.  It's one or the other, and I'd put my money on "bad example."  Anyone else solve this and feel that 5 output is OK?

**Comment by CerebralAdvantage** [comment]
(sigh) on much more careful examination, example 4 output shows precisely what should happen.  The flow is just blocked on one side, and it does a "half stream" process on the other side.  example 4 proves example 5 is incorrect.

**Comment by CerebralAdvantage** [comment]
![image](https://github.com/fchollet/ARC-AGI/assets/36646858/6279ec41-56ce-4796-8561-40245995fa78)
suggested edit of example 5 output...

**Comment by fchollet** [comment]
Thanks for the reports. I issued a fix for this task (live at HEAD).

**Comment by neoneye** [comment]
Side comment. No need to answer this.

Today 2024-july-26, there was this `incorrect` attempt at solving it, I don't know by who. The human didn't get it right.
![79fb03f4_incorrect](https://github.com/user-attachments/assets/892cea12-28d7-40af-902c-16982b60a063)

Looking at historic data in [ARC-Interactive](https://github.com/neoneye/ARC-Interactive-History-Dataset). There are 2 other attempts at solving it, but the users clicked `reveal`, so they are disqualified. I keep the `reveal` solutions around, since it may provide clues to how close a human were to solving it. 

This is with the newest version of this task.
