### ISSUE TITLE
ARC in real world use

### ISSUE THREAD

**Issue by lkelemen** [fchollet/ARC-AGI#17]
Hi,

Is there a plan to make a software which would convert real world scenes/tasks to/from ARC tasks?

I guess this is not trivial to do but it would be worth as AI researchers would be much more interested in ARC if they saw that ARC helps different general AI algos to be tested in real world usage via the converter + ARC.

br
Lajos

**Comment by Alexadar** [comment]
Its a next phase of development of general ai. 

Pay attention that all visual tasks here are quantized to pixels and have not many dots in it because of insane complexity of calculations, which first machines+algorithms would do to solve it. 

After I read white-paper i was amazed how much work it nerds to do to solve even simpler tasks in required general ai way.

**Comment by jmmcd** [comment]
@lkelemen you might be interested in the work of Dileep George and colleagues who have defined and solved tasks which are ARC-like in some ways, but are applicable to real-world robotics. Eg https://arxiv.org/pdf/1812.02788.
