### ISSUE TITLE
Neural Abstract Reasoner: claims that they has achieved 80% accuracy on this dataset

### ISSUE THREAD

**Issue by bransGl** [fchollet/ARC-AGI#82]
I have found  https://arxiv.org/pdf/2011.09860.pdf Neural Abstract Reasoner research.  They has claims tabout 80% accuracy on this dataset. @fchollet  How do you think are they realy got 80% accuracy on a such hard dataset?  Look sucpitious to me.  Can't find code, submissions on kagle, or references on their paper.

**Comment by jmmcd** [comment]
"As this work is still in progress, these are preliminary results evaluated on grids up to 10×10."

I guess this 80% is only on the grids of small sizes, which are disproportionately the "easy" tasks involving mere rotation/mirroring.

**Comment by enceladus2000** [comment]
Has anyone tried implementing this paper? I can't find a working demonstration anywhere.

**Comment by hassanshallal** [comment]
Hi, I worked on ti for a few months 2020. I haven’t read that article yet thought.

Hassan

**Comment by Sebastian-0** [comment]
I think there are several strange things about their paper.
- In a later presentation (2021) they say "NAR achieves 61.13% accuracy on the Abstraction and Reasoning Corpus" with no further explanation. Is that measure on the entire dataset (i.e. all grid sizes)? Otherwise, why is number different? They use the exact same graphs as motivation in their poster as in the old article, yet with different numbers as the result, see: https://eucys2021.usal.es/computing-03-2021/
- As far as I understand it they evaluate on the public test set, yet they compare it to the Kaggle competition which ran on completely different, hidden, tasks.
- They claim to solve 78,8% of 100 hidden tasks but don't explain how they get .8 when the test are binary.
- There is no discussion on what the impact is when excluding all larger grids, this is especially relevant when they are comparing agains the Kaggle competition.
- There is no source code, no one (AFAIK) has reproduced the results, and there is no official benchmark against the hidden test set.

It's possible they have devised an approach that is better than the previous state-of-the-art, but at this point I find it hard to take their numbers at face value.

**Comment by hassanshallal** [comment]
Thank you for sharing your thoughts. I share perspective on some of these points and also noticed the papers used data augmentation. I am not convinced that using deep learning in any shape or form can tackle escalating levels of generalization from local (robustness), to broad (flexibility), and finally to extreme generalization.
