### ISSUE TITLE
310f3251 test is unsolvable, wrap around

### ISSUE THREAD

**Issue by neoneye** [fchollet/ARC-AGI#99]
# Problem

[ARC-Interactive](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=310f3251)

I was unable to solve this task.

My reasoning. 
- Maintain same repeating tile.
- For every non-black pixel, insert a red pixel at relative position -1, -1.

### My predicted solution
![predicted](https://github.com/fchollet/ARC/assets/147971/ec452fe0-ae64-4990-b412-cddaa7f8075c)

### The expected solution
![expected](https://github.com/fchollet/ARC/assets/147971/a4d87a35-66df-47b8-ba49-0dce9324cdd2)

### Difference
![annotated](https://github.com/fchollet/ARC/assets/147971/e4dce08f-ad97-47e7-8428-03f9f6afab21)

My mistake was that I assumed `maintain same repeating tile`, thus assuming that the red pixels would wrap around the edge.

# Solution

Add a `train` pair, that demonstrates that the tiles are non-repeating.

**Comment by neoneye** [comment]
It's better now than before. However there are no priors in the training pairs that demonstrates `no-wrap-around`. IMHO it's somewhat counter intuitive that it's only the `test` pair.

Idea for improvement, tweak one of the `train` pairs to demonstrate that there is no wrapping around when drawing the red pixels.

This task was updated in commit: https://github.com/fchollet/ARC/commit/b7fd42c53f0c26a807ba0b00e42f858d2c11d125

[The task now looks like this in ARC-Interactive](https://neoneye.github.io/arc-staging/edit.html?dataset=ARC&task=310f3251_v2)
![310f3251_v2](https://github.com/fchollet/ARC/assets/147971/87ea54a2-52ab-4f2d-a2dd-4d2c1aa43cf8)

**Comment by CerebralAdvantage** [comment]
Agreed.  It's like this particular puzzle was created and is being maintained by an intern who is unclear on the concept of "train".  No intelligent thing would assume "no local wrapping", because of example 1 and ESPECIALLY example 2.  You need at least one train example that clearly shows this detail.  Otherwise you might was well be shooting for a score of 99.  If there is any evidence to the contrary, please present it.  Without that, our only evidence is that the Test input was changed after the first issue was reported.

**Comment by fchollet** [comment]
Thanks for the reports. I issued a fix for this task (live at HEAD). The fix is to add wraparound and add a task to demonstrate it.
